name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install git
        run: |
          apt-get update -y && apt-get install -y git
          make clean
      - name: Sphinx build
        uses: ammaraskar/sphinx-action@master
        with:
          #build-command: "make clean && make build"
          docs-folder: "./"
      - name: Commit documentation changes
        run: |
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "CI doc updates" -a ||:
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
